// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwvbicrrbqbiwcxszkhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3dmJpY3JyYnFiaXdjeHN6a2hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNDM0ODMsImV4cCI6MjA2NzkxOTQ4M30.x_OWl5-Wsk1kZBd_dd8X67Pwh1-7ypOweKv523mJw-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});