// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rndsgbzkgmkarngyzmkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuZHNnYnprZ21rYXJuZ3l6bWtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NjgwNjcsImV4cCI6MjA2ODI0NDA2N30.Crm3anpbifb_ivcNJO0EDQLJNnVn0O1yn2hfms3gSq0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});